### ISSUE TITLE
"Clear All" button clears grid size from URL

### ISSUE THREAD

**Issue by dare-to-recurse** [sigh/Interactive-Sudoku-Solver#6]
In some update the "Clear All" button has started clearing the grid size from the URL, which breaks the solver until grid size is switched in the drop-down menu.

URL after clicking button:
![url-clear-all-pressed](https://github.com/user-attachments/assets/9db63081-3c6e-4315-8dc5-fda2ca18edd7)

16x16 grid after clicking button:
![grid-clear-all-pressed](https://github.com/user-attachments/assets/6c4e21f7-a2c4-4551-8a50-1ecdd4126550)

**Comment by sigh** [comment]
Pushed a quick fix in https://github.com/sigh/Interactive-Sudoku-Solver/commit/b1f35d94942b0e04de5dfd44f8516d31f7c6c160

I'll look later at making the shape-handling a bit more robust.
